mealplan/api/urls.py
# api/urls.py

from django.urls import path
from .views import RecipeDetailsAPIView, RecipeListAPIView

urlpatterns = [
    path('recipes/<slug:slug>/', RecipeDetailsAPIView.as_view(), name='recipe-detail-api'),
    path('recipes/', RecipeListAPIView.as_view(), name='recipe-list-api'),
]

mealplan/core/urls.py
# urls.py
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('recipe/', include('recipe.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
] + debug_toolbar_urls()

mealplan/recipe/urls.py
# mealplan/urls.py

from django.urls import path
from .views import home, recipe_list, recipe_detail

app_name = "recipe"

urlpatterns = [
    path('', home, name="home"),
    path('recipes/', recipe_list, name="recipe-list"),
    path('recipes/<slug:recipe_name>/', recipe_detail, name="recipe-detail"),
]

mealplan/recipe/models/category.py
"""
Category model
"""
from django.db import models
from django.core.exceptions import ValidationError

import re


class Category(models.Model):
    """Category object"""
    name = models.CharField(max_length=100, unique=True)

    def clean(self):
        """Clean category name field before validation"""
        if not self.name:
            raise ValidationError({'name': 'The name field cannot be empty.'})
        if not re.match(r'^[a-zA-Z\s]+$', self.name):
            raise ValidationError({'name': 'The name field must contain only letters and spaces.'})
        if Category.objects.filter(name__iexact=self.name).exists():
            raise ValidationError({'name': 'A category with this name already exists.'})

    def save(self, *args, **kwargs):
        """Save Category in database"""
        self.clean()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.name}"

mealplan/recipe/models/food.py
"""
Food model
"""
from django.db import models
from django.core.exceptions import ValidationError

import re


class Food(models.Model):
    """Food object"""
    name = models.CharField(max_length=100, unique=True)

    def clean(self):
        """Clean food name field before validation"""
        if not self.name:
            raise ValidationError({'name': 'The name field cannot be empty.'})
        if not re.match(r'^[a-zA-Z\s]+$', self.name):
            raise ValidationError({'name': 'The name field must contain only letters and spaces.'})
        if Food.objects.filter(name__iexact=self.name).exists():
            raise ValidationError({'name': 'A food with this name already exists.'})

    def save(self, *args, **kwargs):
        """Save Food in database"""
        self.clean()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.name}"

mealplan/recipe/models/ingredient.py
"""
Ingredient model
"""
from django.db import models
from django.db.models import UniqueConstraint
from django.core.exceptions import ValidationError

from .food import Food
from .recipe import Recipe
from .unit import Unit


class Ingredient(models.Model):
    """Ingredient object"""
    food = models.ForeignKey(Food, on_delete=models.CASCADE)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    amount = models.FloatField(null=True, blank=True)
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        constraints = [
            UniqueConstraint(fields=['food', 'recipe'], name='unique_food_recipe')
        ]

    def clean(self):
        """Check ingredient amount field before validation"""
        if self.amount is not None and not isinstance(self.amount, (int, float)):
            raise ValidationError({'amount': 'The amount must be a number.'})

        if isinstance(self.amount, float) and self.amount < 0:
            raise ValidationError({'amount': 'The amount cannot be negative.'})

    def save(self, *args, **kwargs):
        """Save Ingredient in database"""
        self.clean()
        super().save(*args, **kwargs)

    def __str__(self):
        """
        Returns a string representation of an ingredient.

         The string includes the amount (if present), the unit (if present), the food name,
        and the recipe name. If the amount is not provided, the format will be:
        - "{food_name} dans {recipe_name}"

        If the amount is provided but no unit is specified, the format will be:
        - "{amount} {food_name} dans {recipe_name}"

        If both amount and unit are provided, the format will be:
        - "{amount} {unit_name} de {food_name} dans {recipe_name}"

        The method ensures no extra spaces are included if the unit is not provided.
        """
        if self.amount is None:
            return f"{self.food.name} in {self.recipe.name}"

        if isinstance(self.amount, float) and self.amount.is_integer():
            amount_str = str(int(self.amount))
        else:
            amount_str = str(self.amount)

        if self.unit:
            unit_name = self.unit.plural_name if self.amount > 1 else self.unit.name
            return f"{amount_str} {unit_name} of {self.food.name} in {self.recipe.name}"
        else:
            return f"{amount_str} {self.food.name} in {self.recipe.name}"

mealplan/recipe/models/recipe.py
from django.db import models
from django.urls import reverse
from .category import Category
from .food import Food


class Recipe(models.Model):
    """
    The information of a recipe. The Recipe model has a many-to-many relationship
    with the Ingredient model. See Ingredient model for more information.
    """
    name = models.CharField(max_length=200)
    servings = models.IntegerField()
    ingredients = models.ManyToManyField(Food, through="Ingredient")
    categories = models.ManyToManyField(Category)
    description = models.TextField(default="Pas encore de description :o")
    slug = models.SlugField(null=False, unique=True, max_length=200)

    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):
        return reverse("recipe_detail", kwargs={"slug": self.slug})

mealplan/recipe/models/unit.py
"""
Unit model
"""
from django.db import models
from django.core.exceptions import ValidationError

import re


class Unit(models.Model):
    """Unit object"""
    name = models.CharField(max_length=50, unique=True)
    short_name = models.CharField(max_length=10, blank=True, null=True)
    plural_name = models.CharField(max_length=50, blank=True, null=True)

    def clean(self):
        """Clean Unit fields before validation"""
        valid_field_regex = re.compile(r'^[A-Za-z\s]+$')

        # Validate `name`
        if not valid_field_regex.match(self.name):
            raise ValidationError({'name': 'The name should only contain letters and spaces.'})

        # Validate `short_name`
        if self.short_name and not valid_field_regex.match(self.short_name):
            raise ValidationError({'short_name': 'The short name should only contain letters and spaces.'})

        # Validate `plural_name`
        if self.plural_name and not valid_field_regex.match(self.plural_name):
            raise ValidationError({'plural_name': 'The plural name should only contain letters and spaces.'})

    def save(self, *args, **kwargs):
        """Save Unit in database"""
        self.clean()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

mealplan/recipe/views.py
"""
Views for recipe web app
"""
from django.shortcuts import render, get_object_or_404
from .models import Category, Ingredient, Recipe


def home(request):
    return render(request, 'recipe/home.html')


def recipe_list(request):
    categories = Category.objects.all()
    recipes = Recipe.objects.prefetch_related('categories').all()

    selected_categories = request.GET.getlist('categories')

    if selected_categories:
        recipes = recipes.filter(categories__id__in=selected_categories)

    return render(request, 'recipe/recipe_list.html', {'recipes': recipes, 'categories': categories})


def recipe_detail(request, recipe_name):
    recipe = get_object_or_404(Recipe.objects.prefetch_related('categories'), slug=recipe_name)
    ingredients_list = Ingredient.objects.filter(recipe=recipe).select_related('food', 'unit')

    context = {
        "recipe": recipe,
        "ingredients_list": ingredients_list,
    }
    return render(request, 'recipe/recipe_detail.html', context)

mealplan/recipe/templates/recipe/base.html
<!-- templates/base.html -->
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Mealplanner App</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
		{% component_css_dependencies %}
	</head>

	<body class="bg-neutral-900 text-white">
		<div>
			<header>
				<nav class="fixed w-full z-50 top-0 start-0 bg-gray-900 border-b border-gray-500">
					<div class="flex justify-between justify-end">
						<!--Sidebar button-->
						<button data-drawer-target="logo-sidebar" data-drawer-toggle="logo-sidebar" aria-controls="logo-sidebar" type="button" class="inline-flex items-center p-2 mt-2 ms-3 text-sm text-gray-500 rounded-lg hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 :text-gray-400 hover:bg-gray-700 focus:ring-gray-600">
							<span class="sr-only">Open sidebar</span>
							<svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
								<path clip-rule="evenodd" fill-rule="evenodd" d="M2 4.75A.75.75 0 012.75 4h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 4.75zm0 10.5a.75.75 0 01.75-.75h7.5a.75.75 0 010 1.5h-7.5a.75.75 0 01-.75-.75zM2 10a.75.75 0 01.75-.75h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 10z"></path>
							</svg>
						</button>

						<!--Navigation links-->
						<ul class="flex items-center p-3 gap-x-3 md:p-5 md:gap-x-5">
							<li>
								<a href="{% url 'recipe:home' %}" class="block py-2 px-3 rounded bg-transparent text-lime-400 p-0" aria-current="page">Meal Plan</a>
							</li>
							<li>
								<button type="button" class="text-white bg-lime-600 hover:bg-lime-700 focus:ring-4 focus:outline-none focus:ring-lime-800 font-medium rounded-lg text-sm px-4 py-2 text-center">
									<a href="{% url 'recipe:recipe-list' %}">Recipes</a>
								</button>
							</li>
						</ul>
					</div>
				</nav>
			</header>

			<!-- Sidebar -->
			<aside id="logo-sidebar" class="fixed top-0 left-0 z-40 w-64 h-screen transition-transform -translate-x-full" aria-label="Sidebar">
			   <div class="h-full px-3 pt-24 overflow-y-auto text-gray-400 bg-gray-900">
				  <span class="self-center text-white text-xl font-semibold">Grocery List</span>
				  <button type="button" id="clear-grocery-list-button" class="text-sm text-white text-center px-4 py-2 ml-12 bg-lime-600 hover:bg-lime-700 focus:ring-lime-800 focus:ring-4 focus:outline-none font-medium rounded-lg">
					Clear
				</button>
				<!-- Grocery list goes here -->
				<ul id="grocery-list" class="space-y-2 font-medium">

				</ul>
			   </div>
			</aside>
		</div>

		<!-- Page content -->
		<div class="container mx-auto mt-28 mb-16">
			{% block content %}
			{% endblock %}
    	</div>

	<!-- Global scripts -->
	<script src="{% static 'recipe/js/common.js' %}"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.0/flowbite.min.js"></script>
	{% component_js_dependencies %}

	<!-- Pages related scripts -->
	<script src="{% static 'recipe/js/modal.js' %}"></script>
	<script src="{% static 'recipe/js/recipe.js' %}"></script>
	<script>
		document.addEventListener('DOMContentLoaded', function() {
			const recipeFilter = new RecipeFilter('/api/recipes/');
		});
	</script>
	</body>
</html>

mealplan/recipe/templates/recipe/home.html
<!-- templates/home.html -->
{% extends "base.html" %}

{% block content %}
<h1 class="text-4xl font-bold text-center mb-16">Meal Plan</h1>
<div class="relative overflow-x-auto mt-10">
    <table class="w-full text-sm text-left rtl:text-right text-gray-400">
        <thead class="text-white text-xs text-center uppercase">
            <tr class="border-b border-gray-500">
                <th scope="col" class="w-36 pb-7">

                </th>
                <th scope="col" class="w-36 pb-7">
                    Monday
                </th>
                <th scope="col" class="w-36 pb-7">
                    Tuesday
                </th>
                <th scope="col" class="w-36 pb-7">
                    Wednesday
                </th>
                <th scope="col" class="w-36 pb-7">
                    Thursday
                </th>
                <th scope="col" class="w-36 pb-7">
                    Friday
                </th>
                <th scope="col" class="w-36 pb-7">
                    Saturday
                </th>
                <th scope="col" class="w-36 pb-7">
                    Sunday
                </th>
            </tr>
        </thead>

        <tbody>
            {% component "cell" text="Breakfast" / %}
            {% component "cell" text="Lunch" / %}
            {% component "cell" text="Snack" / %}
            {% component "cell" text="Dinner" / %}
        </tbody>
    </table>
</div>

<!-- Recipes modal -->
<div id="recipe-modal" tabindex="-1" aria-hidden="true" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
    <div class="relative p-4 w-full max-w-2xl max-h-full">
        <div class="relative rounded-lg shadow bg-gray-700">
            <!-- Modal header -->
            <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t border-gray-500">
                <h3 class="text-xl font-semibold text-white">
                    Select a recipe
                </h3>
                <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center" data-recipe-modal-hide="recipe-modal">
                    <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                    </svg>
                    <span class="sr-only">Close</span>
                </button>
            </div>
            <!-- Modal Content -->
            <div id="recipe-modal-content" class="p-4 md:p-5 space-y-4">
                <!-- Recipes list goes here -->
            </div>
        </div>
    </div>
</div>
{% endblock %}

mealplan/recipe/templates/recipe/recipe_detail.html
<!-- templates/recipe_detail.html -->
{% extends "base.html" %}

{% block content %}
<div class="px-4">
    <h1 class="text-2xl md:text-4xl font-bold text-center mb-12 sm:mb-16">{{ recipe.name }}</h1>

    <div>
        <h2 class="text-lg md:text-2xl font-bold mb-6">
            Ingredients for
        
            {% if recipe.servings > 1 %}
                {{ recipe.servings }} servings
            {% else %}
                {{ recipe.servings }} serving
            {% endif %}
        </h2>

        <ul class="text-gray-400">
        {% for ingredient in ingredients_list %}
            <li>
                {% if ingredient.amount %}
                    {% if ingredient.amount == 0.5 %}
                        1/2
                    {% else %}
                        {{ ingredient.amount|stringformat:"2f"|floatformat:"-2"|default:'' }}
                    {% endif %}
                {% endif %}

                {% if ingredient.unit %}
                    {% if ingredient.unit.short_name %}
                        {{ ingredient.unit.short_name }} of
                    {% else %}
                        {% if ingredient.amount > 1 %}
                            {{ ingredient.unit.plural_name }} of
                        {% else %}
                            {{ ingredient.unit.name }} of
                        {% endif %}
                    {% endif %}
                {% endif %}
                
                {{ ingredient.food.name }}
            </li>
        {% endfor %}
        </ul>
    </div>

    <div class="mt-6">
        <h2 class="text-lg md:text-2xl font-bold mb-6">Instructions</h2>
        <p class="text-gray-400">{{ recipe.description }}</p>
    </div>
</div>
{% endblock %}

mealplan/recipe/templates/recipe/recipe_list.html
<!-- templates/recipe_list.html -->
{% extends "base.html" %}

{% block content %}
<div class="flex justify-between items-center mb-14 sm:mt-28">
    <h1 class="text-2xl sm:text-4xl font-bold pl-4 sm:pl-0">Recipes</h1>

    <form>
        <label for="default-search" class="mb-2 text-sm font-medium text-gray-400 sr-only">Search</label>
        <div class="relative">
            <div class="absolute top-3.5 inset-y-0 start-0 ps-3 pointer-events-none">
                <svg class="w-4 h-4 text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
                </svg>
            </div>
            <div class="flex mr-2 sm:mr-0">
                <input type="search" id="search-dropdown" class="block p-2.5 pl-9 w-full text-sm text-gray-400 rounded-s-2 rounded-s-lg border bg-gray-700 border-gray-600 placeholder-gray-400 focus:ring-0 focus:border-lime-700" placeholder="Search" required>
                <button id="dropdown-button" data-dropdown-toggle="dropdown" class="flex-shrink-0 inline-flex items-center z-10 py-2.5 px-4 text-sm font-medium rounded-e-lg bg-gray-600 border border-s-0 border-gray-600 hover:bg-gray-700 focus:ring-2 focus:ring-lime-700" type="button">
                    <span class="hidden sm:block">Categories</span>
                    <svg class="w-2.5 h-2.5 ms-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
                    </svg>
                </button>
            </div>
        </div>

        <div id="dropdown" class="hidden w-44 z-10 divide-y divide-gray-100 bg-gray-700 rounded-lg">
            <ul id="recipe-categories" class="space-y-2 p-4 text-sm" aria-labelledby="dropdown-button">
                {% for category in categories %}
                <li class="flex items-center">
                    <input id="{{ category.id }}" type="checkbox" name="categories" value="{{ category.name }}"
                        class="w-4 h-4 rounded bg-gray-600 text-lime-600 focus:ring-0 focus:ring-offset-0" />
                    <label for="{{ category }}" class="ml-2 text-sm text-gray-100 font-medium">
                        {{ category }}
                    </label>
                </li>
                {% endfor %}
            </ul>
        </div>
    </form>
</div>

<ul id="recipe-list" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4 gap-4">
    {% for recipe in recipes %}
        <li class="recipe-item">
            <div class="flex flex-col place-content-around h-60 p-4 rounded-lg bg-gray-800 border border-gray-700 shadow-md shadow-gray-700">
                <a class="self-center h-2/6" href="{{ recipe.slug }}">
                    <h5 class="recipe-name text-center mb-2 text-xl font-bold tracking-tight text-white">{{ recipe.name }}</h5>
                </a>
                <ul class="flex flex-wrap justify-center content-between h-1/4">
                    {% for category in recipe.categories.all %}
                        {% component "badge" text=category / %}
                    {% endfor %}
                </ul>
                <a href="{{ recipe.slug }}" class="inline-flex items-center w-32 ml-auto px-3 py-2 text-sm text-center text-white font-medium rounded-lg bg-lime-600 hover:bg-lime-700 focus:ring-4 focus:outline-none focus:ring-lime-800">
                    Full recipe
                    <svg class="rtl:rotate-180 w-3.5 h-3.5 ms-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
                    </svg>
                </a>
            </div>
        </li>
    {% endfor %}
</ul>
{% endblock %}